src/SparkPost.Tests/DataMapperTests.cs
src/SparkPost/DataMapper.cs

Continued #10, but with tests.

Send booleans instead of strings

---

src/.nuget/packages.config
src/SparkPost.Portable/PortableReflectionExtensions.cs
src/SparkPost.Portable/SparkPost.Portable.csproj
src/SparkPost.Portable/packages.config
src/SparkPost.sln
src/SparkPost/Content.cs

This makes the client library available for use in Xamarin.iOS, Xamarin.Android and other compliant Portable libraries (PCL Profile 7)

SparkPost portable for use in Xamarin.iOS, Xamarin.Android (PCL Profile 7)

---

src/SparkPost.Tests/SparkPost.Tests.csproj
src/SparkPost.Tests/SuppressionTests.cs
src/SparkPost.Tests/app.config
src/SparkPost.Tests/packages.config
src/SparkPost.sln
src/SparkPost/Client.cs
src/SparkPost/DataMapper.cs
src/SparkPost/IClient.cs
src/SparkPost/ISuppressions.cs
src/SparkPost/ITransmissions.cs
src/SparkPost/ListSuppressionResponse.cs
src/SparkPost/ListTransmissionResponse.cs
src/SparkPost/RequestSender.cs
src/SparkPost/Response.cs
src/SparkPost/RetrieveTransmissionResponse.cs
src/SparkPost/SparkPost.csproj
src/SparkPost/SparkPost.nuspec
src/SparkPost/Suppression.cs
src/SparkPost/Suppressions.cs
src/SparkPost/SuppressionsQuery.cs
src/SparkPost/Transmissions.cs
src/SparkPost/UpdateSuppressionResponse.cs

Suppression List support, bonus Retrieve Transmission

---

src/SparkPost.Tests/DataMapperTests.cs
src/SparkPost/Options.cs

Add `InlineCss` property to Options

---

src/SparkPost.Tests/DataMapperTests.cs
src/SparkPost/Options.cs

Add IP Pool to options

---

src/SparkPost.Tests/RequestMethodFinderTests.cs
src/SparkPost.Tests/RequestMethods/DeleteTests.cs
src/SparkPost.Tests/RequestMethods/GetTests.cs
src/SparkPost.Tests/RequestMethods/PostTests.cs
src/SparkPost.Tests/RequestMethods/PutTests.cs
src/SparkPost.Tests/SparkPost.Tests.csproj
src/SparkPost/IRequestMethod.cs
src/SparkPost/RequestMethodFinder.cs
src/SparkPost/RequestMethods/Delete.cs
src/SparkPost/RequestMethods/Get.cs
src/SparkPost/RequestMethods/Post.cs
src/SparkPost/RequestMethods/Put.cs
src/SparkPost/RequestMethods/PutAndPostAreTheSame.cs
src/SparkPost/RequestMethods/RequestMethod.cs
src/SparkPost/RequestSender.cs
src/SparkPost/SparkPost.csproj

Drop the switch for an open-closed solution.  Added tests, etc.  
I ran this against all four verbs, and I sent an email.  It's all fine.

Refactor the request methods

---

src/SparkPost.Tests/ListMessageEventsResponseTests.cs
src/SparkPost.Tests/SparkPost.Tests.csproj
src/SparkPost/Client.cs
src/SparkPost/ListMessageEventsResponse.cs
src/SparkPost/MessageEvent.cs
src/SparkPost/MessageEvents.cs
src/SparkPost/PageLink.cs

Just making message events line up with the rest of the library.
It still works:

Message Event cleanup

---

README.md

Update Travis badge to point to csharp-sparkpost

---

src/SparkPost.Tests/SuppressionTests.cs
src/SparkPost/InboundDomainResponse.cs
src/SparkPost/JsonStuff.cs
src/SparkPost/ListInboundDomainResponse.cs
src/SparkPost/ListRelayWebhookResponse.cs
src/SparkPost/ListSubaccountResponse.cs
src/SparkPost/ListWebhookResponse.cs
src/SparkPost/MessageEvent.cs
src/SparkPost/MessageEvents.cs
src/SparkPost/Request.cs
src/SparkPost/RequestMethods/Get.cs
src/SparkPost/RequestMethods/PutAndPostAreTheSame.cs
src/SparkPost/RetrieveRelayWebhookResponse.cs
src/SparkPost/RetrieveWebhookResponse.cs
src/SparkPost/SparkPost.csproj
src/SparkPost/Subaccounts.cs
src/SparkPost/Suppressions.cs
src/SparkPost/Transmissions.cs
src/SparkPost/Utilities/Jsonification.cs

This is related to #48, hopefully it might assist?  
This PR just consolidates the JSON-ification, which I'm thinking will make it easier to make a global config changes.

Consolidate the json encoding

---

src/SparkPost/Attributes.cs
src/SparkPost/Client.cs
src/SparkPost/DataMapper.cs
src/SparkPost/IClient.cs
src/SparkPost/IRecipientLists.cs
src/SparkPost/RecipientList.cs
src/SparkPost/RecipientLists.cs
src/SparkPost/RetrieveRecipientListsResponse.cs
src/SparkPost/SendRecipientListsResponse.cs
src/SparkPost/SparkPost.csproj

Hi SparkPost Team,
I have added the RecipientList API operation to the Client of it. Please have a look, if it is okay, help to merge it and update the nuget in the future. 
Thanks very much.
Frank Zhang

add the operation of  RecipientList API

---

examples/BCC/BCC.csproj
examples/BCC/Program.cs
examples/BCC/Properties/AssemblyInfo.cs
examples/BCC/packages.config
examples/CC/CC.csproj
examples/CC/Program.cs
examples/CC/Properties/AssemblyInfo.cs
examples/CC/packages.config
examples/Examples.sln
examples/SendInline/Program.cs
examples/SendInline/Properties/AssemblyInfo.cs
examples/SendInline/SendInline.csproj
examples/SendInline/packages.config
examples/SendTemplate/Program.cs
examples/SendTemplate/Properties/AssemblyInfo.cs
examples/SendTemplate/SendTemplate.csproj
examples/SendTemplate/packages.config
examples/app.config

Example projects share a solution and app.config and are held under /examples/.

Added basic examples projects

---

src/SparkPost/IRecipientLists.cs
src/SparkPost/RecipientList.cs
src/SparkPost/RecipientLists.cs

Minor stuff, just fix a couple things.

Cleanup recipient lists

---

.gitattributes
src/SparkPost/Client.cs
src/SparkPost/CreateTemplateResponse.cs
src/SparkPost/DataMapper.cs
src/SparkPost/ITemplates.cs
src/SparkPost/RetrieveTemplateResponse.cs
src/SparkPost/SparkPost.csproj
src/SparkPost/Template.cs
src/SparkPost/TemplateContent.cs
src/SparkPost/TemplateOptions.cs
src/SparkPost/Templates.cs

This is a copy of #44, but with master merged in.

Templates support 2 - Merged Master

---

examples/BCC/Program.cs
examples/CC/Program.cs
examples/SendInline/Program.cs
examples/SendTemplate/Program.cs

Just making this consistent with the rest of the library. :smile: @ewandennis

Spaces not tabs in examples

---

src/SparkPost/IClient.cs

Hi @darrencauthon ,
In the IClient need add Templates to expose the templates to the client. So I add that. Please review and merge it. Thanks very much.

add the template to IClient

---

src/SparkPost/Templates.cs

@darrencauthon , I have added some fields which need for the response. Would please have a review and merge and release with nuget. Thanks very much.

add some fields which need for response

---

src/SparkPost.Acceptance/RecipientLists.feature
src/SparkPost.Acceptance/RecipientLists.feature.cs
src/SparkPost.Acceptance/SparkPost.Acceptance.csproj
src/SparkPost.Acceptance/TransmissionSteps.cs
src/SparkPost.Acceptance/Transmissions.feature
src/SparkPost.Acceptance/Transmissions.feature.cs
src/SparkPost.Acceptance/testtextfile.txt
src/SparkPost.Tests/FileTests.cs
src/SparkPost.Tests/SparkPost.Tests.csproj
src/SparkPost/File.cs

These are the changes from #116 from @asherber, but with integration tests that show that they work.

File helpers with integration tests

---

src/SparkPost.Tests/TransmissionTests.cs
src/SparkPost/Address.cs
src/SparkPost/SparkPost.csproj
src/SparkPost/Transmission.cs
src/SparkPost/Utilities/MailMessageMapping.cs

Just some cleanup before morning @asherber 's work.  There's a lot of work to convert a mail message to a transmission, so I thought it would be best if we kept that work in a separate class.

Mailmessage parsing with cleanup

---

src/SparkPost.Tests/DataMapperTests.cs
src/SparkPost/CcHandling.cs

This just includes a test for the whitespace check for an email address, and some refactoring.
Related to #140

Add test to #140, and refactor

---

src/SparkPost.Tests/ClientTests.cs
src/SparkPost/Client.cs
src/SparkPost/RequestSenders/AsyncRequestSender.cs
src/SparkPost/SparkPost.csproj
src/SparkPost/Utilities/StringHelper.cs

User the user agent to start tracking users of this library.
Requested by mhillyer via slack.
Tested here:

User agent

---

src/SparkPost.Tests/DataMapperTests.cs
src/SparkPost/DataMapper.cs

A conversation on Slack... I never meant to switch metadata to snake_case.
Since this is potentially a breaking change, I am going to have to deploy this as a major version release.

Do not alter metadata keys
