darrencauthon/csharp-sparkpost

src/SparkPost/Properties/AssemblyInfo.cs, src/SparkPost/SparkPost.nuspec
This is meant to allow the library to work with 4.5 and greater.
I don't know if these changes specifically did it, though.  Perhaps the versioning update fixed it, or perhaps the previous build was just against 4.5.2.  But the main point is that the lib was assigned to "45" instead of "452" so it seems to work.
=> Downgrade from 452 to 45

src/SparkPost/DataMapper.cs
Options property should be serialized as boolean values and not the string counterpart, as that will throw a "field 'options.open_tracking' is of type 'string', but needs to be of type 'boolean'" error from the API.
fixes #10
=> Ouput boolean values instead of strings

src/SparkPost/RequestSender.cs
This is meant to resolve #17 .
So, apparently JSON.Net has global settings that can change how it operates.  People that change these global settings could inadvertently break how this library works.
This library's needs for json serialization were meant to run with the default settings, so I've passed those to get JSON.Net to ignore the global settings.
=> Force type handling to off

src/SparkPost.Tests/DataMapperTests.cs, src/SparkPost/CcHandling.cs, src/SparkPost/DataMapper.cs, src/SparkPost/Recipient.cs, src/SparkPost/RecipientType.cs, src/SparkPost/SparkPost.csproj
BCC comes for free, as emails to multiple recipients are kept from each other.  But I'm keeping BCC option in there to avoid "how do I send BCC?" question... and in case some sort of solution is created around it.
CC is a little more awkward, as a user originally had to create a comma-separated list of CC'd email addresses from the list of recipients.  I changed this so that a ```RecipientType``` of To/CC/BCC can be set on a recipient.  So users won't have to deal with the header - the library will do all of the work.
=> Add support for CC and BCC

AUTHORS.md, src/SparkPost.Portable/SparkPost.Portable.csproj, src/SparkPost/Client.cs, src/SparkPost/IClient.cs, src/SparkPost/ITransmissions.cs, src/SparkPost/SparkPost.csproj, src/SparkPost/Transmissions.cs
This will make it easier to mock SparkPost when unit testing consumers of the .NET API wrapper.
Closes #24
=> Add interfaces for Client and Transmissions classes

src/SparkPost.Tests/ClientTests.cs, src/SparkPost.Tests/SparkPost.Tests.csproj, src/SparkPost/Client.cs, src/SparkPost/RequestSender.cs
This is meant to resolve #38.
This change allows a user to override how the ```HttpClient``` that the library uses to be changed.  
```c#
client.CustomSettings.BuildHttpClientsUsing(() => new HttpClient());
// or pass your own custom one ^^^
```
Every time a web request is made, it will call the provided function.  If none is provided, it will default to ```new HttpClient()``` like it always has used.
=> Allow custom http client

src/SparkPost.Tests/DataMapperTests.cs, src/SparkPost/DataMapper.cs
This should resolve #49.
The library uses conventions to turn objects into a common form that will work for the SparkPost http API.  It does things like turn ```EmailAddress``` into ```email_address```.
However, the last place we probably want to apply these conventions is the substitution data.  That should be passed raw.
=> Pass substitution data raw

src/SparkPost.Tests/DataMapperTests.cs, src/SparkPost/DataMapper.cs
With this fix, both recipient-specific substitution data  and template substitution data (which was fixed with #52) should both be working as expected.
=> Do not alter recipient substitution data keys

src/SparkPost/DataMapper.cs
It's ok to just modify the one that is provided.
The dictionary is not returned because we need a new instance, but because I want to be able to just call ```return RemoveNulls(x);```
=> Create one less dictionary object

src/SparkPost.Tests/SparkPost.Tests.csproj, src/SparkPost.Tests/Utilities/SnakeCaseTests.cs, src/SparkPost/DataMapper.cs, src/SparkPost/RequestMethods/Get.cs, src/SparkPost/SparkPost.csproj, src/SparkPost/Utilities/SnakeCase.cs, src/SparkPost/ValueMappers/StringObjectDictionaryValueMapper.cs
This is a shared detail, so it would be better to keep it in its own place instead of tied to a specific implementation of the data mapper.
=> Refactor snake case

src/SparkPost.Tests/RequestSenders/AsyncRequestSenderTests.cs, src/SparkPost.Tests/SparkPost.Tests.csproj, src/SparkPost/Client.cs, src/SparkPost/IClient.cs, src/SparkPost/RequestSenders/AsyncRequestSender.cs
Here are some unit tests targeting ```AsyncRequestSender```. Given its nature and the fast iterations that started this library, this code was only covered in integration tests.  Now that things are settled and it is pretty clean, it's time to get unit tests on this thing.
=> Add tests around the request building

src/SparkPost.Tests/InboundDomainTests.cs, src/SparkPost.Tests/SparkPost.Tests.csproj, src/SparkPost/Client.cs, src/SparkPost/DataMapper.cs, src/SparkPost/IClient.cs, src/SparkPost/InboundDomain.cs, src/SparkPost/InboundDomainResponse.cs, src/SparkPost/InboundDomains.cs, src/SparkPost/ListInboundDomainResponse.cs, src/SparkPost/SparkPost.csproj
Sorry for dumping this on you without a PR, but I needed this functionality for myself so I wrote it quickly.
Here is the test harness that I used to test:
static void Main(string[] args)
{
var apiKey = "<API Key>";
var inboundDomain = "test.example.com";
var client = new SparkPost.Client(apiKey);
var create = client.InboundDomains.Create(new InboundDomain { Domain = inboundDomain }).Result;
var list = client.InboundDomains.List().Result;
Debug.Assert(list.InboundDomains.Count() == 1);
Debug.Assert(list.InboundDomains.First().Domain == inboundDomain);
var retrieve = client.InboundDomains.Retrieve(inboundDomain).Result;
Debug.Assert(retrieve.InboundDomain.Domain == inboundDomain);
var delete = client.InboundDomains.Delete(inboundDomain).Result;
Debug.Assert(delete);
}
=> Added support for inbound domains

src/SparkPost.Tests/RelayWebhookTests.cs, src/SparkPost.Tests/SparkPost.Tests.csproj, src/SparkPost/Client.cs, src/SparkPost/DataMapper.cs, src/SparkPost/IClient.cs, src/SparkPost/ListRelayWebhookResponse.cs, src/SparkPost/RelayWebhook.cs, src/SparkPost/RelayWebhooks.cs, src/SparkPost/RetrieveRelayWebhookResponse.cs, src/SparkPost/SparkPost.csproj
Apologies again for springing this on you. I know I should raise an issue first, but I was in a rush to get a project out. You know how it goes :wink: 
Here is the test harness I used. In order to test you need to create an inbound domain using my previous PR   #68.
static void Main(string[] args)
{
var apiKey = "<Api Key>";
var client = new SparkPost.Client(apiKey);
var relayWebhook = new RelayWebhook
{
Name = "Test",
AuthToken = "34395f35-3c29-497f-8a5a-57a4db7d28fc",
Target = "https://webhooks.customer.example/replies",
Match = new RelayWebhookMatch { Domain = "test.example.com" }
};
var create = client.RelayWebhooks.Create(relayWebhook).Result;
var list = client.RelayWebhooks.List().Result;
Debug.Assert(list.RelayWebhooks.Count() == 1);
Debug.Assert(list.RelayWebhooks.First().Name == …
=> Added support for Relay Webhooks

src/SparkPost.Tests/DataMapperTests.cs, src/SparkPost.Tests/RelayWebhookTests.cs, src/SparkPost.Tests/SparkPost.Tests.csproj, src/SparkPost/Client.cs, src/SparkPost/DataMapper.cs, src/SparkPost/IClient.cs, src/SparkPost/ListRelayWebhookResponse.cs, src/SparkPost/RelayWebhook.cs, src/SparkPost/RelayWebhooks.cs, src/SparkPost/RetrieveRelayWebhookResponse.cs, src/SparkPost/SparkPost.csproj
Review of #69 with only superficial changes.  Great work! :smile:
=> Relay webhooks review

docker/Dockerfile, docker/build_and_deploy.sh, docker/readme.md
This docker container will pull the latest version of this library, create a nuget package, and deploy it to Nuget.
The only thing is needs is a valid Nuget API key, from someone that has rights to publish the package to Nuget.
```
cd docker
docker build .  # this will produce a hash key, say 12345678
docker run -e "APIKEY=your_nuget_key_here" 12345678
```
This container has been registered on Docker Hub, and can be run like so:
```
docker run -e "APIKEY=your_nuget_key_here" darrencauthon/csharp-sparkpost
```
=> Docker instance to build & deploy to nuget

docker/Dockerfile, src/SparkPost/SparkPost.nuspec
It seems that when using Mono to build the package via the nuspec, each dll has to be added manually.
Plus, the nuget commandline version that comes with Mono (today) is very old. Upgraded that to the most recent before pushing the library.
=> Manually select files

docker/Dockerfile, docker/build_and_deploy.sh
Sigh.
But it seems to have finally worked.  Version 1.6.1 was just deployed with this script.
https://www.nuget.org/packages/SparkPost/1.6.1
=> More mono nuget fixes

src/SparkPost.Tests/ClientTests.cs, src/SparkPost/Client.cs
Resharper caught this for me.  Noticed the subaccount being passed in the constructor was gray, as it was unused.  Seems like that would be a helpful thing to use.  Sorry for the goof.
=> If a subaccount is passed in the constructor, SET IT.

docker/Dockerfile, docker/build_and_deploy.sh, src/SparkPost/SparkPost.nuspec
This is a workaround for the nuget issue I am having (https://github.com/NuGet/Home/issues/2833).
Since the nupkg file that is created by the nuget command is invalid due to some zip issue, I unzip the nupkg and zip it up with a different zip app.  That seems to get around the problem.
=> Figure this docker issue out

examples/BCC/Program.cs, examples/CC/Program.cs, examples/SendInline/Program.cs, examples/SendTemplate/Program.cs
@ewandennis 
I'm switching out the ```.Wait()``` call here with a setting to go to ```Sync``` mode.  
I'm doing this because there are areas, where for reasons I don't want to think about, the ```.Wait()``` call will hang.  Like a MVC action.  I've fielded multiple questions on this, which is why I stopped suggesting people use ```Wait()``` or "figure it out."  This mode will perform the "wait" in a way that will not cause a hang in a MVC action.
=> Make sync explicit

src/SparkPost.Tests/FileTests.cs, src/SparkPost.Tests/SparkPost.Tests.csproj, src/SparkPost/File.cs
I've added some `File.Create<T>()` factory methods for more easily creating attachments and inline images from files, byte arrays, and streams.
=> Add factory methods for File

src/SparkPost.Tests/TransmissionTests.cs, src/SparkPost/Address.cs, src/SparkPost/Transmission.cs
Hi Darren,
Since users may already have existing code that creates a `MailMessage` and sends via SMTP, I thought it would be useful to be able to create a `Transmission` from that. So I've addded:
```csharp
public Transmission(MailMessage message): this()
{
Parse(message);
}
public void Parse(MailMessage message)
{
...
}
```
`Parse` will pull in all the address fields, text and html bodies, subject, and attachments. 
I also dropped in some alternate constructors for `Address` to make them a little cleaner, on the analogy of `MailAddress`.
=> Ability to work with MailMessage

src/SparkPost/Transmission.cs
As discussed in #124 , this pull request brings back the ```LoadFrom``` method.  // cc @asherber
=> Bring back the LoadFrom method.

src/SparkPost.Tests/TransmissionTests.cs, src/SparkPost/Transmission.cs
As discussed on #124.
I think it would be better to keep the ```Transmission``` class as isolated from ```MailMessage``` as possible, and I don't want to create confusion from people who think that they must or should use a ```MailMessage``` to create a ```Transmission```.  
So this pull request just removes the constructor that takes a mail message, and replaces it with a static helper.  
Since ```MailMessage``` is in the .Net framework, I think it's ok to have the static helpers in the POCO object's class.
=> Static helper for the construction of a transmission from a mail message

src/SparkPost.Tests/DataMapperTests.cs, src/SparkPost/CcHandling.cs, src/SparkPost/DataMapper.cs
Fixes #43 
One consequence of this handling is that if there are any copied recipients (CC or BCC), there must be exactly one To recipient, and it must have an address. 
Right now I've got guard conditions in the method which throw an exception if either of these conditions is not true. I think your MO in this library tends more towards not throwing any exceptions up front and letting the API return an error if there are any issues. If you'd rather do things this way, I can adjust. Should we just not do any rewriting at all if these conditions aren't met? Or should we add the CC header but not do any address rewriting? My concern is that these will lead to odd results for which the reason may not be apparent to the user; an exception will indicate what the issue is.
=> Cc handling

src/SparkPost/CcHandling.cs
I realized after using some of this code in another project that it wasn't handling well the (edge) case where a CC recipient had an `Address.Email` that was whitespace and needed to go in the CC header. This case would in any event run into problems downstream when attempting to send to that address, but this is is a tidier way of handling the header. Nothing urgent.
=> Refactor for case where Email is whitespace

src/SparkPost.Acceptance/TransmissionSteps.cs, src/SparkPost.Acceptance/Transmissions.feature, src/SparkPost.Acceptance/Transmissions.feature.cs
Just a test around the attachments issue.
If you send an email as a template, any attachments will not be included.  Sorry, that's just how the SparkPost API works -- it's not this library.
=> Tests around the template/attachment issue

README.md
Hey Darren 👋 
This is a small docs change to show that the hostname for the API is configurable. I'm not too familiar with C# so let me know if I totally misunderstood the code 😬
=> Adding docs for a custom hostname
